[wip] Merge libraries into a single file Separating libraries into their own file might increase readability, but it is painful to find the location of the file. So, utility functions are better kept together in the main file.

diff --git a/dotfile b/dotfile
--- a/dotfile
+++ b/dotfile
@@ -10,23 +10,213 @@ readonly DOTFILE_DEBUG=${DEBUG:-0}
 readonly DOTFILE_LOG_LEVEL=${LOG_LEVEL:-2}
 
 # XDG base directories
+readonly XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
 readonly XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
 readonly XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
 
 ## Logging functions
 ################################
 
-# Source logging library
-. _functions/logging.sh
+# Color constants
+readonly BLACK=$(tput setaf 0)
+readonly RED=$(tput setaf 1)
+readonly GREEN=$(tput setaf 2)
+readonly YELLOW=$(tput setaf 3)
+readonly BLUE=$(tput setaf 4)
+readonly MAGENTA=$(tput setaf 5)
+readonly CYAN=$(tput setaf 6)
+readonly WHITE=$(tput setaf 7)
+
+# Text style constants
+readonly BOLD=$(tput bold)
+readonly UNDERLINE=$(tput smul)
+readonly BLINK=$(tput blink)
+
+# Reset test to normal style
+readonly NORMAL=$(tput sgr0)
+
+debug() {
+    [ "$DOTFILE_DEBUG" -eq 0 ] && [ "$DOTFILE_LOG_LEVEL" -lt 3 ] && return
+    printf "[${BOLD}${WHITE}DEBUG${NORMAL}] ${WHITE}%s${NORMAL}\n" "$@" >&2
+}
+
+info() {
+    [ "$DOTFILE_LOG_LEVEL" -lt 2 ] && return
+    printf "[${BOLD}${BLUE}INFO${NORMAL}] ${WHITE}%s${NORMAL}\n" "$@" >&2
+}
+
+warn() {
+    [ "$DOTFILE_LOG_LEVEL" -lt 1 ] && return
+    printf "[${BOLD}${YELLOW}WARNING${NORMAL}] ${WHITE}%s${NORMAL}\n" "$@" >&2
+}
+
+error() {
+    printf "[${BOLD}${RED}ERROR${NORMAL}] ${WHITE}%s${NORMAL}\n" "$@" >&2
+}
+
 
 ## Utility functions
 ################################
 
-# Source stack library
-. _functions/stack.sh
+## Push a new item to stack
+stack_push() {
+    # Syntax: stack_push <stack_id> <item>
 
-# Source checker library
-. _functions/checks.sh
+    if [ "$#" -ne 2 ]; then
+        error "Usage: stack_push <stack_id> <item>"
+        return 1
+    fi
+
+    local stack_id item
+    stack_id="$1"
+    item="$2"
+
+    eval "stack_$stack_id=\"\${stack_$stack_id} $item\""
+}
+
+## Pop an item from stack to stdout
+stack_pop() {
+    # Syntax: stack_pop <stack_id>
+
+    if [ "$#" -ne 1 ]; then
+        error "Usage: stack_pop <stack_id>"
+        return 1
+    fi
+
+    local stack_id result
+    stack_id="$1"
+    result=$(eval "echo \${stack_$stack_id}" | awk -F ' ' '{ print $NF }')
+
+    # Check if the result is empty
+    if [ -z "$result" ]; then
+        warn "Stack is already empty."
+        return
+    fi
+
+    # Remove the item from the end
+    eval "stack_$stack_id=\$(echo \"\${stack_$stack_id}\" | sed -e 's/ $result$//')"
+
+    # Print the last element to stdout
+    echo $result
+}
+
+## Print the content of the stack
+stack_print() {
+    # Syntax: stack_print <stack_id>
+
+    if [ "$#" -ne 1 ]; then
+        error "Usage: stack_print <stack_id>"
+        return 1
+    fi
+
+    local stack_id
+    stack_id="$1"
+
+    eval "echo \${stack_$stack_id}"
+}
+
+## Print the name of the stack
+stack_name() {
+    # Syntax: stack_name <stack_id>
+
+    if [ "$#" -ne 1 ]; then
+        error "Usage: stack_name <stack_id>"
+        return 1
+    fi
+
+    local stack_id
+    stack_id="$1"
+
+    echo "stack_$stack_id"
+}
+
+## Ensure a command succeeds
+ensure() {
+    if ! "$@"; then
+        error "Command failed: $*"
+        error "This command is required. Cannot proceed..."
+        exit 1
+    fi
+}
+
+## Maybe a command exists
+maybe() {
+    is $1 a command?
+    yes && "$@" || debug "No such command: $1"
+}
+
+## is-checks
+is() {
+    # Syntax: is <subject> a/an <complement>?
+
+    local subject article complement
+    subject="$1"
+    article="$2"
+    complement=$(echo "$3" | sed -e 's/\?$//')
+
+    if [ "$#" -ne 3 ] || [ "$article" != "a" ] && [ "$article" != "an" ]; then
+        error "Usage: is <subject> a(n) <complement>?"
+        return 1
+    fi
+
+    case "$complement" in
+        command) command -v "$subject" > /dev/null ;;
+        file) [ -e "$subject" ] ;;
+        directory) [ -d "$subject" ] ;;
+        symlink) [ -L "$subject" ] ;;
+
+        *)
+            error "<complement> can be either command, file, directory, or symlink."
+            false
+            ;;
+    esac && checks_last_result="yes" || checks_last_result="no"
+}
+
+## does-checks
+does() {
+    # Syntax: does <subject> <verb> <object>?
+
+    local subject verb object
+    subject="$1"
+    verb="$2"
+    object=$(echo "$3" | sed -e 's/\?$//')
+
+    if [ "$#" -ne 3 ]; then
+        error "Usage: does <subject> <verb> <object>?"
+        return 1
+    fi
+
+    case "$verb" in
+        contain) does_contain "$subject" "$object" ;;
+
+        *)
+            error "<verb> must be contain."
+            false
+            ;;
+    esac && checks_last_result="yes" || checks_last_result="no"
+
+}
+
+## Check if the "array" contains the item
+does_contain() {
+    local array item occurrence
+    array=$1
+    item=$2
+    occurrence=$(printf "%s\n" $(eval "echo \"\$$array\"") | grep -c "^$item$")
+
+    [ "$occurrence" -ne 0 ]
+}
+
+## Yes check
+yes() {
+    [ "$checks_last_result" = "yes" ]
+}
+
+## No check
+no() {
+    [ "$checks_last_result" != "yes" ]
+}
+
 
 ## Dependency list creator
 depends() {
@@ -56,7 +246,7 @@ append() {
     item=$1
     to=$2
     array=$3
-    
+
     if [ $# -ne 3 ] || [ "$to" != "to" ]; then
         error "Usage: append <item> to <array>"
         exit 1
@@ -73,8 +263,23 @@ append() {
 
 ## Install native package dependencies
 install_native() {
-    info "Installing native package dependencies..."
-    info "You might need to provide your sudo credential here."
+    debug "Installing native packages: $@"
+
+    # Check if the user can access sudo
+    if ! sudo -v -p "Installing native packages requires sudo:"; then
+        printf "%s\n" $@ > $XDG_CACHE_HOME/native_pkgs.txt
+
+        if ! [ dotfile_sudo_warned ]; then
+            warn "This account doesn't seem to have sudo access!"
+            warn "You may have to install some packages yourself."
+            warn "Refer to the native_pkgs.txt in ${XDG_CACHE_HOME} directory"
+            warn "after this command exits."
+
+            dotfile_sudo_warned="yes"
+        fi
+        return
+    fi
+
     # TODO: support other platforms as well
     #sudo pacman -Sy "$@"
     #sudo apt-get install "$@"
@@ -105,9 +310,9 @@ COMMANDS:
     help         Displays this help message.
 EOF
 
-    if [ "$DOTFILE_DEBUG" -ne 0 ]; then
-        echo "    shell        Create a REPL instance. Useful when debugging functions."
-    fi
+if [ "$DOTFILE_DEBUG" -ne 0 ]; then
+    echo "    shell        Create a REPL instance. Useful when debugging functions."
+fi
 }
 
 dotfile_init() {
@@ -162,6 +367,12 @@ dotfile_init() {
 }
 
 dotfile_install() {
+    if [ "$#" -ne 1 ]; then
+        error "You must provide one package!"
+        error "Usage: dotfile install <package>"
+        return 1
+    fi
+
     local pkg
     pkg="$1"
 
@@ -265,16 +476,16 @@ dotfile_shell() {
     if [ "$DOTFILE_DEBUG" -eq 0 ]; then
         error "Opening shell is not supported if DEBUG environment variable is not set!"
         exit 1
-    fi
+        fi
 
-    while true; do
-        read -r -p "dotfile> " line
+        while true; do
+            read -r -p "dotfile> " line
 
-        [ "$line" = "exit" ] && break
+            [ "$line" = "exit" ] && break
 
-        eval "$line"
-    done
-}
+            eval "$line"
+        done
+    }
 
 ## Entrypoint
 ################################
@@ -288,13 +499,30 @@ if [ -z "$action" ]; then
 fi
 shift
 
-case "$action" in
-    help)
-        echo "dotfile -- automatic dotfile installer, because I am lazy as fuck"
-        echo ""
-        dotfile_usage
-        ;;
+# Display help message
+if [ "$action" = "help" ]; then
+    echo "dotfile -- automatic dotfile installer, because I am lazy as fuck"
+    echo ""
+    dotfile_usage
+    exit
+fi
 
+# If there is no dotfile configuration file, instruct the user to run
+# `dotfile init` first
+is "$XDG_CONFIG_HOME/dotfile.conf" a file?
+if no && [ "$action" != "init" ]; then
+    error "Dotfile manager is not initialized yet!"
+    error "Please run \"dotfile init\" first."
+    exit 1
+fi
+
+# Go to the dotfile home directory
+ensure . "$XDG_CONFIG_HOME/dotfile.conf"
+debug "Changing directory to $dotfile_home..."
+dotfile_old_pwd="$(pwd)"
+cd "$dotfile_home"
+
+case "$action" in
     init)
         dotfile_init "$@"
         ;;
@@ -324,4 +552,7 @@ case "$action" in
         dotfile_usage
         ;;
 esac
+
+# Restore the directory
+cd "$dotfile_old_pwd"
 
